apiVersion: apps/v1
kind: Deployment
metadata:
  name: bouda
  namespace: dev
  labels:
    app: bouda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bouda
  template:
    metadata:
      labels:
        app: bouda
    spec:
      containers:
      - name: bouda
        image: nexus.do/bouda:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: dock